services:
  - type: web
    name: hacker-sequence-backend
    env: node
    plan: free
    rootDir: .
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: COUNTDOWN_SECONDS
        value: 10
      - key: CLIENT_ORIGINS
        sync: false
      - key: VIDEO_URL
        sync: false
      - key: IMAGE_URL
        sync: false
